services:
  - type: web
    name: git-commit-telegram-bot
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
      - key: KEMAL_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false